export const ROOMS_FETCH_ROOM         = 'ROOMS_FETCH_ROOM';
export const ROOMS_FETCH_ROOM_TOKEN   = 'ROOMS_FETCH_ROOM_TOKEN';
export const ROOMS_INIT_ROOM          = 'ROOMS_INIT_ROOM';
export const ROOMS_SET_SUBSCRIBERS    = 'ROOMS_SET_SUBSCRIBERS';
export const ROOMS_SET_ACTIVE_INDEX   = 'ROOMS_SET_ACTIVE_INDEX'; 
export const ROOMS_SET_LOCAL_STREAM   = 'ROOMS_SET_LOCAL_STREAM';
export const ROOMS_UPDATE_PROPS       = 'ROOMS_UPDATE_PROPS';