default: &default
  service_id: 5c31550a2198f58f9c332068
  service_key: 623
  nuve_host: http://localhost:3000/
  DB_HOST: localhost
  DB_USER: root
  DB_PASSWORD:
  DB_NAME: add_project_development

development:
  <<: *default
  
test:
  <<: *default
  DB_NAME: add_project_test