default: &default
  service_id: 5c3083c8b43d2dd02231eafe
  service_key: 19191
  nuve_host: http://localhost:3000/
  DB_HOST: localhost
  DB_USER: root
  DB_PASSWORD:
  DB_NAME: add_project_development

development:
  <<: *default
  
test:
  <<: *default
  DB_NAME: add_project_test